### ISSUE TITLE
SQLite?

### ISSUE THREAD

**Issue by jackyliang** [TomLingham/Laravel-Searchy#10]
Hi there

Your description says:

    Searchy is an; easy-to-use, light-weight, MySQL only

I was wondering would this work for SQlite?

**Comment by TomLingham** [comment]
Hi @jackyliang,

It's possible. I'm not entirely sure as I haven't tested it to be honest - feel free to have a go and let me know if it works! I would be happy to look into updating it to work with SQLite for version 2.1 if that is a use case you would be interested in.

Thanks for the message!
