### ISSUE TITLE
SQLite Testing Environment

### ISSUE THREAD

**Issue by FutureFutureTo** [TomLingham/Laravel-Searchy#103]
Does this package work w/ a sqlite testing environment?

I'm getting the following error when using 'TEST' as the query string:

```
+errorInfo: array:3 [
        0 => "HY000"
        1 => 1
        2 => "near "'T%E%S%T%'": syntax error"
      ]
```

The query in my controller is as follows:
```
$query      = Searchy::search('products')
            ->fields('title', 'producer')
            ->query($q)
            ->getQuery()
            ->having('relevance', '>', 20)
            ->limit(20)
            ->pluck('id')
            ->toArray();
```

**Comment by TomLingham** [comment]
Unfortunately, this package only works with a MySQL database. It uses MySQL specific features to calculate match relevance.
