### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by necenzurat** [TomLingham/Laravel-Searchy#106]
Yea, was wondering if is this project is still maintained. 
Cheers.

**Comment by TomLingham** [comment]
Not actively. I would probably accept PR's but there are no tests cases to confirm them and I don't really participate in the PHP community any more (haven't used it actively for 2-3) and thus don't have an environment set up.

**Comment by necenzurat** [comment]
well can yo at least make it Laravel 6.0 compatible?

**Comment by TomLingham** [comment]
I've updated the composer.json and cut a new release (2.0.19)

Again, I'm not actually sure this works - I don't have the time to confirm the change but happy to take PR's if there is more work involved. Thanks for the interest in the 6.0 support.
