### ISSUE TITLE
Full hits on string is not included in result with the Levenshtein-driver

### ISSUE THREAD

**Issue by roberts91** [TomLingham/Laravel-Searchy#107]
Hello
First of all - thank you for creating this package. It's a really good addition to Laravel.
I found an issue with the Levenshtein-driver, but keep in mind that I might be mistaken. It might still be worth looking into.

The problem is - when you use the Levenshtein-driver - that the matches that has 0 in "distance" from the search string is not included in the query. This is due to the following code:

_src/SearchDrivers/BaseSearchDriver.php:128 (version 2.0.19)_
```php
return $this->query
            ->orderBy($this->relevanceFieldName, 'desc')
            ->having($this->relevanceFieldName, '>', 0);
```

The having-clause causes the full match to be exlcuded in this case since the distance (stored in the relevance-column) is 0. In my opinion the having-clause should only be applied to the other drivers except the Levenshtein-driver. Is this something that maybe should be changed? And is this project open for PR's?

Kind regards,
Robert S.

**Comment by TomLingham** [comment]
Please see Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
