### ISSUE TITLE
How to also include a related model in the result?

### ISSUE THREAD

**Issue by SapneshNaik** [TomLingham/Laravel-Searchy#108]
I'm trying to use `with()` without any success.

```php
public function search(Request $request)
    {
        $value = $request->input('value');

        return Searchy::users('login_id', 'alternate_phone_number')
             ->select('id',
                    'login_id',
                    'alternate_phone_number')
            ->query($value)
            ->getQuery()
            ->with('addresses')
            ->where('base_role', 'Parent')
            ->limit(10)
            ->get();
    }
```

How can I fetch a related model?

**Comment by qerim** [comment]
@SapneshNaik you can use [hydrate](https://laravel.com/api/5.8/Illuminate/Database/Eloquent/Builder.html#method_hydrate) to turn array items into a Eloquent Model collection:

    $value = $request->input('value');

    $users_arr = Searchy::users('login_id', 'alternate_phone_number')
         ->select('id',
                'login_id',
                'alternate_phone_number')
        ->query($value)
        ->getQuery()
        ->where('base_role', 'Parent')
        ->limit(10)
        ->get();

    return User::hydrate($users_arr->toArray())->load('addresses');
