### ISSUE TITLE
Support for Laravel 7?

### ISSUE THREAD

**Issue by SapneshNaik** [TomLingham/Laravel-Searchy#109]
I'm not able to install this package in Laravel 7. any help?

**Comment by damms005** [comment]
For anyone having this issue still, you can temporarily edit your `composer.json` file to use the [fork](https://github.com/damms005/Laravel-Searchy/tree/laravel-7-support) I created.

I have also [submitted a PR](https://github.com/TomLingham/Laravel-Searchy/pull/112) that simply bumps `illuminate/support` dependency to the version required by Laravel 7.

**Comment by TomLingham** [comment]
closed by #110
