### ISSUE TITLE
Could not load package tom-lingham/searchy in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ^7.*: Invalid version string "^7.*"

### ISSUE THREAD

**Issue by AlexGodbehere** [TomLingham/Laravel-Searchy#114]
When trying to install this package with `composer require tom-lingham/searchy ^2.0` I'm getting the following error. Is this an issue with the package? I'm running Laravel 7.

```
Could not load package tom-lingham/searchy in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ^7.*: Invalid version string "^7.*"
```

**Comment by tanmuhittin** [comment]
Just update the composer version from 1.10.11

Ref : https://stackoverflow.com/questions/63801165/composer-could-not-load-package-invalid-version-string

**Comment by AlexGodbehere** [comment]
This solved it, thanks!
