### ISSUE TITLE
Composer Minimum Stability

### ISSUE THREAD

**Issue by owalerys** [TomLingham/Laravel-Searchy#12]
I installed this repository but instead of specifying "2.*", I had to specify "2.*@dev" to meet composer's minimum stability requirements for my default installation of Laravel 5.1. I was getting an error that the package could not be found (can also be caused by minimum stability incompatibility). Is this expected?

Below is my Laravel composer.json file

    {
        "name": "laravel/laravel",
        "description": "The Laravel Framework.",
        "keywords": ["framework", "laravel"],
        "license": "MIT",
        "type": "project",
        "require": {
            "php": ">=5.5.9",
            "laravel/framework": "5.1.*",
            "tom-lingham/searchy" : "2.*@dev"
        },
        "require-dev": {
            "fzaninotto/faker": "~1.4",
            "mockery/mockery": "0.9.*",
            "phpunit/phpunit": "~4.0",
            "phpspec/phpspec": "~2.1"
        },
        "autoload": {
            "classmap": [
                "database"
            ],
            "psr-4": {
                "App\\": "app/"
            }
        },
        "autoload-dev": {
            "classmap": [
                "tests/TestCase.php"
            ]
        },
        "scripts": {
            "post-install-cmd": [
                "php artisan clear-compiled",
                "php artisan optimize"
            ],
            "pre-update-cmd": [
                "php artisan clear-compiled"
            ],
            "post-update-cmd": [
                "php artisan optimize"
            ],
            "post-root-package-install": [
                "php -r \"copy('.env.example', '.env');\""
            ],
            "post-create-project-cmd": [
                "php artisan key:generate"
            ]
        },
        "config": {
            "preferred-install": "dist"
        }
    }

**Comment by TomLingham** [comment]
Wow... I never tagged the releases! I hope I didn't cause you too many headaches. Fixed now.

Thanks for letting me know :)
