### ISSUE TITLE
Objects not returned

### ISSUE THREAD

**Issue by stanwarri** [TomLingham/Laravel-Searchy#13]
From the doc. It said the result returns an object array. However I only getting a normal array. What is the way to return an object array.

**Comment by jbrooksuk** [comment]
Better yet, collections. This would allow results to be mapped, filtered etc without having to call `collect`.

**Comment by danieliancu** [comment]
+1
Most of the time I end up mapping the objects for relationships.

**Comment by TomLingham** [comment]
The docs say it returns an array of objects. I don't want to change this as this is the default data that is returned from the Laravel Database Query Object and this adding an unnecessary layer of responsibility.

Wont Fix.
