### ISSUE TITLE
Multiple tables?

### ISSUE THREAD

**Issue by 93gaurav93** [TomLingham/Laravel-Searchy#14]
How can I search through multiple tables connected with foreign keys?

**Comment by TomLingham** [comment]
Hi @93gaurav93, You can't at the moment with Searchy. It's only meant to provide a very simple interface for searching. My suggestion is to return the ID's that you need from the search results and then do your eloquent stuff with that.

**Comment by TheRealJAG** [comment]
Would be nice to be able to search multiple tables. For instance get all the books or authors LIKE %jon%
