### ISSUE TITLE
Search Trashed

### ISSUE THREAD

**Issue by kadeprice** [TomLingham/Laravel-Searchy#15]
Is there anyway that your package can return trashed results? 
By adding a flag, or indicator can the query results will return trashed items. I'm thinking something like
 app()->searchy->assets('model', 'serial', 'service_tag', 'asset_tag')->query($search)->withTrashed()->get();

The DB::table should return all results, but at some point the search results filter out the soft deleted items.

**Comment by TomLingham** [comment]
Hmm... haven't touched the code in a while so can't remember what I am doing off the top of my head that would be filtering the trashed objects. Yes, it should return them using the Query Builder ... as far as I know.

I'll take a peek at this in the next few weeks. Happy for you to submit a pull request if you'd like to see it resolved sooner. Or, if you can see where they are getting filtered out, I'll jump in and make the necessary updates as it's an important use case :smile: 

Thanks for letting me know about this one.

**Comment by S3D-Jake** [comment]
I am getting all results, even soft deleted. Raw SQL confirms theres nowhere in the software filtering soft deletes. I would check how your calling it.

**Comment by jakeboyles** [comment]
https://github.com/TomLingham/Laravel-Searchy/pull/26
