### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by jbrooksuk** [TomLingham/Laravel-Searchy#17]
> Big sidenote; I'm one of the founders of StyleCI.

You should look at [StyleCI](https://styleci.io) for automatic code standards fixing. We can automate the entire process of fixing, pull request and merging for you too.

**Comment by TomLingham** [comment]
Great! Thanks for the heads up ... looks like something I could really use :joy:

**Comment by jbrooksuk** [comment]
I wasn't being sarcastic or anything :)

**Comment by TomLingham** [comment]
I know, it's all good. I just know that I can be a bit messy sometimes so could use something like StyleCI to keep me on my toes :+1:

**Comment by jbrooksuk** [comment]
:)
