### ISSUE TITLE
Eager Loading and Query Scope

### ISSUE THREAD

**Issue by chrislandeza** [TomLingham/Laravel-Searchy#22]
Hi, is there a way to use queryScope or Eager load using this package?

On my User Model I have this scope:

    /**
     * Active Users.
     */
    public function scopeActive($query)
    {
        return $query->where('active', 1);
    }

Now I want to get/filter just the active user. I tried this code but it didn't work:

    $users = Searchy::users('name')->query('John Smith')->active()->get();

    Call to undefined method TomLingham\Searchy\SearchDrivers\FuzzySearchDriver::active()

I also tried to eager load the roles of my user using 'with' method but no luck.

    $users = Searchy::users('name')->query('John Smith')->with('roles')->get();

    Call to undefined method TomLingham\Searchy\SearchDrivers\FuzzySearchDriver::with()

Any possible solution? Thanks.

**Comment by TomLingham** [comment]
Sorry, not really... well not nicely. Though you can get around it without too much trouble.

In your case you could go:

```
// This will return an instance of the Laravel Database Query Builder
$users = Searchy::users('name')->query('John Smith')->getQuery();

// This will create a new User instance and then you can access the scope
// function directly which then applies the where clause and returns the query.
// Finally running get() to return the records
$usersScoped = (new User())->scopActive( $users )->get();
```

I haven't tested but this should do what you are after :smile:

**Comment by TomLingham** [comment]
Because it uses the database query builder and not Eloquent, you will have to tackle eager loading differently. What I normally do is return the ID's of all the results using Searchy and then pass them into an eloquent query. Otherwise, no Searchy doesn't support anything as specific as that.

**Comment by chrislandeza** [comment]
yeah.. I ended up plucking the 'id' of my search result and do a manual Eloquent query.

    // search the users table 
    $hits = Searchy::users('name')->query($query)->get();
     
    // Pluck the 'id' from the search result.
    $ids = array_pluck($hits, 'id');

    // return just the active users and eager load the roles
    $this->user->whereIn('id', $ids)->active()->with('roles')->get();
