### ISSUE TITLE
Nullable fields don't work as expected

### ISSUE THREAD

**Issue by danieliancu** [TomLingham/Laravel-Searchy#23]
Awesome package Tom!
Thank you very much!

Say you got the following table schema:

```sql
CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `col1` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `col2` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `col3` varchar(30) CHARACTER SET utf8 DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

As you can see `col3` is allowed `NULL` values.

```php
Searchy::test('col1', 'col2', 'col3')->query('test')->get()
```

will give an empty array even if there are values matching query in `col1` and `col2`.

```php
Searchy::test('col1', 'col2')->query('test')->get()
```

gives the appropriate results.

I did some further testing and found out that when using nullable fields for searching into, if at least one of them is `NULL` then the whole row is ignored, even if there are matches in other fields.

**Comment by TomLingham** [comment]
Thanks! I'm really glad you like it!

Thanks for submitting that. That looks very strange. It's a use case i
never considered but you are correct. I'll take a look at this in a couple
days when I'm back at it for the new year and get it all fixed up.

Thanks again :)

**Comment by danieliancu** [comment]
Thanks for the reply.

Well, it's justified to have nullable columns for optional fields.

Happy new year!

**Comment by salarAsadi** [comment]
I have the Same problem. please fix. Thanks for your lightweight library.
