### ISSUE TITLE
Strange syntax error

### ISSUE THREAD

**Issue by danieliancu** [TomLingham/Laravel-Searchy#24]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'having `relevance` > ? order by `relevance` desc limit 100' at line 3 (SQL: select *, IF(name = 'admin', 100, 0) + IF(name LIKE 'admin%', 50, 0) + IF(name LIKE 'A% D% M% I% N%', 42, 0) + IF(REPLACE(name, '\.', '') LIKE '%a%d%m%i%n%', ROUND(40 * (CHAR_LENGTH( 'admin' ) / CHAR_LENGTH( REPLACE(name, ' ', '') ))), 0) + IF(name LIKE 'admin%', 35, 0) + IF( CHAR_LENGTH( TRIM(name)) = CHAR_LENGTH( REPLACE( TRIM(name), ' ', '')) AND name LIKE BINARY 'A%D%M%I%N%', 32, 0) + IF(name LIKE '%admin%', 30, 0) + 8 * ROUND ((
CHAR_LENGTH(name) - CHAR_LENGTH( REPLACE ( LOWER(name), lower('admin'), ''))
) / LENGTH('admin')) AS relevance having `relevance` > 0 order by `relevance` desc limit 100)

**Comment by danieliancu** [comment]
Found the issue.

I was extending a vendor model and searching like so:

```php
Searchy::search($this-table)->fields($fields)
```

But the parent model was setting it's connection in the constructor using a config option and not defining the `$table` property, so it ended up as null.
As soon as I defined the `$table` property, it picked it up and there were no issues.

Maybe add a check or something?

**Comment by TomLingham** [comment]
Thanks for updating. Good idea. I will leave this one open for the time being so I don't forget about it :)

**Comment by TomLingham** [comment]
Wont fix.
