### ISSUE TITLE
Syntax error when searching "key" column

### ISSUE THREAD

**Issue by danieliancu** [TomLingham/Laravel-Searchy#25]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = 'global', 100, 0) + IF(key LIKE 'global%', 50, 0) + IF(key LIKE 'G% L% O% ' at line 1 (SQL: select *, IF(key = 'global', 100, 0) + IF(key LIKE 'global%', 50, 0) + IF(key LIKE 'G% L% O% B% A% L%', 42, 0) + IF(REPLACE(key, '\.', '') LIKE '%g%l%o%b%a%l%', ROUND(40 * (CHAR_LENGTH( 'global' ) / CHAR_LENGTH( REPLACE(key, ' ', '') ))), 0) + IF(key LIKE 'global%', 35, 0) + IF( CHAR_LENGTH( TRIM(key)) = CHAR_LENGTH( REPLACE( TRIM(key), ' ', '')) AND key LIKE BINARY 'G%L%O%B%A%L%', 32, 0) + IF(key LIKE '%global%', 30, 0) + 8 * ROUND ((
CHAR_LENGTH(key) - CHAR_LENGTH( REPLACE ( LOWER(key), lower('global'), ''))
) / LENGTH('global')) AS relevance from `table` having `relevance` > 0 order by `relevance` desc limit 100)

**Comment by TomLingham** [comment]
Thanks, @danieliancu.

Any chance you could post a bit of your code as well?

**Comment by danieliancu** [comment]
I will contribute to the package when I have some time, I think it has great potential.

**Comment by danieliancu** [comment]
```php
Searchy::table('key')->query('global')->get()
```

**Comment by TomLingham** [comment]
It's possibly to do with `key` being a reserved word in MySQL and how the query is being built. I'll take a closer look at this one soon :smile:

**Comment by danieliancu** [comment]
@TomLingham have you thought of adding multiple tables support? I saw a closed issue.

**Comment by danieliancu** [comment]
@TomLingham thank you very much!

**Comment by danieliancu** [comment]
@TomLingham it's because of the reserved keyword
This works:

```php
Searchy::table('`key`')->query('global')->get()
```

and gives appropriate results.

**Comment by TomLingham** [comment]
@danieliancu I have considered it but don't think I will be implementing it. If there are more advanced requirements for searching, then realistically Searchy isn't the right tool for the job. It's only really meant to be a drop in searching tool for smaller projects.

**Comment by TomLingham** [comment]
Great! Thanks @danieliancu I thought that would be the case. I will fix this up in the code soon. Just have to wrap the table names and probably wouldn't hurt to have some tests to run.

**Comment by danieliancu** [comment]
@TomLingham you mean the column names, right?

**Comment by danieliancu** [comment]
@TomLingham what I like the most about this package, is that it's built the laravel way - easy to use and gets the job done

**Comment by danieliancu** [comment]
@TomLingham Thank you!
