### ISSUE TITLE
FUNCTION [dbname].ROUND does not exist

### ISSUE THREAD

**Issue by FrostyX** [TomLingham/Laravel-Searchy#28]
### Issue

On my hosting I got this error:

    SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION regfmri2.ROUND does not exist (SQL: select *, IF(CONCAT(id, ' ', first_name, ' ', last_name) = 'foo', 100, 0) + IF(CONCAT(id, ' ', first_name, ' ', last_name) LIKE 'foo%', 50, 0) + IF(CONCAT(id, ' ', first_name, ' ', last_name) LIKE 'F% O% O%', 42, 0) + IF(REPLACE(CONCAT(id, ' ', first_name, ' ', last_name), '\.', '') LIKE '%f%o%o%', ROUND(40 * (CHAR_LENGTH( 'foo' ) / CHAR_LENGTH( REPLACE(CONCAT(id, ' ', first_name, ' ', last_name), ' ', '') ))), 0) + IF(CONCAT(id, ' ', first_name, ' ', last_name) LIKE 'foo%', 35, 0) + IF( CHAR_LENGTH( TRIM(CONCAT(id, ' ', first_name, ' ', last_name))) = CHAR_LENGTH( REPLACE( TRIM(CONCAT(id, ' ', first_name, ' ', last_name)), ' ', '')) AND CONCAT(id, ' ', first_name, ' ', last_name) LIKE BINARY 'F%O%O%', 32, 0) + IF(CONCAT(id, ' ', first_name, ' ', last_name) LIKE '%foo%', 30, 0) + 8 * ROUND ((
    CHAR_LENGTH(CONCAT(id, ' ', first_name, ' ', last_name)) - CHAR_LENGTH( REPLACE ( LOWER(CONCAT(id, ' ', first_name, ' ', last_name)), lower('foo'), ''))
    ) / LENGTH('foo')) AS relevance from `subjects` having `relevance` > 0 order by `relevance` desc)

Which is caused by `+ 8 * ROUND ((` contained in the code above. For some reason, the space between `ROUND` and openning bracket `(` makes the MySQL parser think, that the `ROUND` is a table name. See <http://stackoverflow.com/a/12566366/3285282>.

### Solution
Please, generate the SQL query in a way, that it contains

    + 8 * ROUND((

instead of

    + 8 * ROUND ((

### Database version

    MySQL [regfmri2]> SHOW VARIABLES LIKE "%version%";
    +-------------------------+----------------+
    | Variable_name           | Value          |
    +-------------------------+----------------+
    | protocol_version        | 10             |
    | version                 | 5.0.67         |
    | version_comment         | SUSE MySQL RPM |
    | version_compile_machine | x86_64         |
    | version_compile_os      | suse-linux-gnu |
    +-------------------------+----------------+

Please note that this issue doesn't occur on my dev machine with MySQL 5.6.27.

**Comment by jbrooksuk** [comment]
:+1:
