### ISSUE TITLE
Returning empty result for search with multiple column

### ISSUE THREAD

**Issue by ranjeet21r** [TomLingham/Laravel-Searchy#33]
$results = Searchy::search('table_name')->fields(['series_name', 'feature_title'])->query('Batman')->get();

this returning empty results and 

$results = Searchy::search('table_name')->fields('series_name')->query('Batman')->get();

This is working fine and returning results.

**Comment by TomLingham** [comment]
Hi @ranjeet21r. Is this perhaps related to #23? What does your data look like?

**Comment by ranjeet21r** [comment]
Hi @TomLingham . Ya sorry i forgot to update the issue. 

I alter columns property to None. before it was set to Nullable and it starts working. 

Thanks for such great pacakge. It save my lots of work. :+1:

**Comment by TomLingham** [comment]
Duplicate of #23

**Comment by AlexDubstone** [comment]
Sehr geehrte Damen und Herren,

ich befinde mich bis zum 26.04. im Urlaub und kann Ihre Anfrage nicht entgegennehmen. In dringenden Fällen erreichen Sie meinen Kollegen Herrn Ussath unter der Rufnummer 0351 / 321 317 23.

Vielen Dank und viele Grüße aus Asien
Alexander Selle
