### ISSUE TITLE
Return Eloquent collection

### ISSUE THREAD

**Issue by vinkla** [TomLingham/Laravel-Searchy#35]
When you do a search today an array is returned when running `get()`. Is it possible to make it return an Eloquent collection?

**Comment by ArturGrigio** [comment]
This isn't a solution by any means, but after tinkering with this repo for the last 20 mins (trying to add a `->first()`) I came up with this solution. Maybe this will help you with your problem:

    $users = Searchy::users('name', 'email')->query('John Smith')->get();
    if($users) {
        $id = $users[0]->id;
        return \App\User::find($id);
    }

**Comment by vinkla** [comment]
Thanks for reaching out @ArturGrigio but that would mean I've to execute multiple queries. Was hoping there would be away around that wouldn't require another query to the database.

**Comment by TomLingham** [comment]
See commit 8566a0a
