### ISSUE TITLE
Not working with L5.2

### ISSUE THREAD

**Issue by folkevil** [TomLingham/Laravel-Searchy#38]
I got this error when use Searchy with L5.2

`Call to undefined method Illuminate\Foundation\Application::bindShared() `

It's because bindShared() have been replaced with singleton(). Please update  #it. Thank you

**Comment by mstnorris** [comment]
I'm using it with 5.2.31 and it's working fine. Followed the setup as per the docs.

**Comment by TomLingham** [comment]
Can't reproduce. @folkevil we already have logic in place to ensure the correct method is used.

```
    public function registerSearchy()
    {
        // Laravel <= 5.1
        $closure = function ($app) {
            return new SearchBuilder( $app['config'] );
        };


        if ( method_exists($this->app, 'bindShared') )
        {
            $this->app->bindShared('searchy', $closure);
        }

        // Laravel 5.2 Goodness :)
        else {
            $this->app->singleton('searchy', $closure);
        }
    }
```

What version of Searchy are you using?
