### ISSUE TITLE
Not working with russian text

### ISSUE THREAD

**Issue by Alexmg86** [TomLingham/Laravel-Searchy#40]
Hi. 
Not working with russian text, english working normal.
If i trying find something on Russian, he return all position

**Comment by TomLingham** [comment]
Hi @Alexmg86. Can you please send me through a sample sql file to the email address on my profile? I will see what I can do.

**Comment by TomLingham** [comment]
Thank you very much for sending through the file!

Can you please update to the latest version (2.0.11), and follow the instructions [here](https://github.com/TomLingham/Laravel-Searchy#unicode-characters-support) to change the Search Driver to the new FuzzySearchUnicodeDriver. This should hopefully fix your issue.

Please note: The FuzzySearchUnicodeDriver does not sanitize your query search before using it in a MySQL query so you will have to ensure it is sanitized yourself.

If you need more help getting that to work, let me know 😄 .

**Comment by Alexmg86** [comment]
Nice. Big thanks!!!

**Comment by TomLingham** [comment]
Great! Thank you!
