### ISSUE TITLE
Search query not returning results with expected relevance score.

### ISSUE THREAD

**Issue by carbontwelve** [TomLingham/Laravel-Searchy#45]
I don't know if this is a bug with your library or simply me not configuring it correctly but I have got searchy working and searching an index table containing content scraped from my website.

To better explain what I am doing, imagine an index table that has the following row (among many others):
```
{
    id: 1,
    body: "Product Name&reg; This product is really good at solving problems with cold and flu"
}
```

I have been using `->having('relevance', '>', 20)` and if I search that table with the query "product name" it will return the one matching row, however if I search it with the query "product name cold and flu" it will return nothing. The expected result is that it should return the same thing, probably with a higher relevancy score.

**Comment by TomLingham** [comment]
Hmm... that is unusual. If you remove the relevance limit do you get any result? If you do, what relevance score does it return?

**Comment by carbontwelve** [comment]
When the relevancy filter is removed everything being returned has a relevancy of 1 or 2. I think I need to modify the weightings of the `FuzzySearchDriver` matchers and see if it helps make things more relevant as I am searching within a _index_ of sanitized body content as opposed to using this as a search for a crud interface.

**Comment by TomLingham** [comment]
Yes, generally if it isn't returning what you are after I would suggest rolling your own Matcher and search driver based on the type of data that you have. Searchy is targeted at shorter strings and the type of searching you are looking for is generally very slow. A matcher similar to the following should do something closer to what you are after:

```php
<?php

class ChunksMatcher extends BaseMatcher
{
    protected $operator = 'LIKE';

    public function formatSearchString($searchString)
    {
        return implode('%', explode(' ', $searchString)).'%';
    }
}
```
and then juts include it in your own search driver. This is similar to the start of string matcher but excludes the space before the word to make it start on the words. On large sets of data this will be fairly slow however.
