### ISSUE TITLE
Question: How can I use relations?

### ISSUE THREAD

**Issue by Kolesar** [TomLingham/Laravel-Searchy#47]
Dear,

Searchy is amazing tool. Thanks for sharing.

I have question about using Larave-Searchy. How can I use relations or Eloquent `with` method during searcing?

**Comment by Kolesar** [comment]
I have found solution with `join` methods after call `getQuery`. Unfortunately `with` is not option, but works :)

**Comment by sevenpointsix** [comment]
@Kolesar Could you possibly post an example of your solution?

**Comment by sevenpointsix** [comment]
To answer my own question above, this appears to work. Here, I'm searching through a table of products, where each product can have a matching record in the "brands" table (joined by products.brand_id), and identifying a match against either the product title or brand title for the word 'test':

    Searchy::products('products.title','brands.title')
        ->select('products.*')
        ->query('test')
        ->getQuery()           
        ->leftJoin('brands', 'products.brand_id', '=', 'brands.id')
        ->get();

**Comment by Kolesar** [comment]
Yes, I use like that! And I detect that does not support for pagination :(, but, with little trick I really hope so it will work with your suggestion in documentation.

**Comment by TomLingham** [comment]
I don't have any intentions to support relations directly using searchy. It already exposes the Laravel builder object and building that functionality into Searchy would just be doubling up - and I doubt I could do as good of a job as Taylor in that case.  I will leave this open incase others are looking for this as I have answered this a few times 😄

**Comment by TomLingham** [comment]
Closing now as I think people have got the point 😄
