### ISSUE TITLE
Using Searchy with non default DB Connection

### ISSUE THREAD

**Issue by skylerkatz** [TomLingham/Laravel-Searchy#49]
I am a huge fan of the package, and was wondering if it would be possible to override the default database connection that searchy uses.  If there is not currently this functionality, I would be interested in contributing that type of functionality, but do not know exactly where in your package that type of configuration would go.

Thanks for what you are doing for the Laravel Community!

**Comment by skylerkatz** [comment]
Realized I could do 'connection.tablename'.

**Comment by skylerkatz** [comment]
It seems that after upgrading to Laravel 5.3 using the `connection.tablename` syntax no longer works.  In looking at the Laravel 5.3 upgrade guide, I do not believe there are any changes to the connection manager that would be causing this to stop working.  Any ideas on your end would be appreciated.

Thanks

**Comment by TomLingham** [comment]
@skylerkatz is this still a problem for you?
