### ISSUE TITLE
Pagination of results

### ISSUE THREAD

**Issue by ankhuve** [TomLingham/Laravel-Searchy#51]
Hey! 

Just installed Searchy and the searching itself works great. However, I'm wondering if it's possible to paginate the results?

I'm comparing it to using the Query Builder and paginating the results as such:

```
    $jobMatches = Job::where('title', 'like', $searchQuery)
        ->orWhere('description', 'like', $searchQuery)
        ->paginate($this->numPerPage)
        ->sortByDesc('published_at')
        ->all();
```

I would love to do the same thing, something like this:

```
    $jobMatches = Searchy::search('jobs')
        ->fields('title', 'description')
        ->query($searchQuery)
        ->getQuery()
        ->having('relevance', '>', 10)
        ->paginate($this->numPerPage)
        ->get();
```

Am I missing something obvious to make this work, or is this just something I'll have to dream of? :smile:

**Comment by ankhuve** [comment]
Allright, I read through the old issues and solved the pagination by doing this:

        $jobMatches = Searchy::search('jobs')
            ->fields('title', 'description')
            ->query($searchQuery)
            ->getQuery()
            ->having('relevance', '>', 10)
            ->skip($rowsToSkip)
            ->take($numPerPage)
            ->get();

Maybe someone with the same problem might find this helpful.

**Comment by TomLingham** [comment]
Great! Thanks. Leaving this one open for reference as it's been asked a few time 😄

**Comment by sml2h3** [comment]
Great!I have the same issues just now

**Comment by sml2h3** [comment]
Searchy::qtn('title', 'name')
->query('d')
->getQuery()
->simplePaginate(2);

**Comment by Kolesar** [comment]
I have many relations, so when searching I returned only ID, and after using 'standard' query with `whereIn('id', ...)`

I know it is slow, but I in this case pagination works, relations works, ... because I get standard Eloquent object

**Comment by gags88** [comment]
@ankhuve You can also use `limit` instead of `take`

**Comment by gags88** [comment]
@sml2h3 ... only simplePaginate works.. however, it would be wonderful if `paginate` method also works

**Comment by TomLingham** [comment]
There are technical limitations that meant this can't easily be improved inside the library without blowing it out of it's original scope which is something that I don't want to do.
