### ISSUE TITLE
Searchy is using table name instead of model name?

### ISSUE THREAD

**Issue by Sennik** [TomLingham/Laravel-Searchy#53]
Searchy::**users**('name', 'email')->query('John Smith')->get();

I expect users in this example to be a modelname but instead it is the table name. Why not use the modelname and take advantage of the model's configuration?

**Comment by TomLingham** [comment]
Searchy searches tables in your MySQL Database using SQL queries, not using models so wouldn't make sense to use the model name. You can, however, pass an eloquent model through to the search method:

```php
Searchy::search(Users)->query('John Smith')->get();
```

But Searchy is simply pulling the table name from the model anyway so it's up to you if you think that makes sense or not.
