### ISSUE TITLE
use searchy on query object

### ISSUE THREAD

**Issue by Rezakhaan** [TomLingham/Laravel-Searchy#55]
first I do:
 $query = Searchy::search('advertisements');
            $query= $query->fields('title')->query(Input::get('title'))
                ->getQuery()->having('relevance', '>', 50);

again after this I need to do another query with searchy on $query which I have made before,
How can I do this,plz help :(

**Comment by TomLingham** [comment]
Hmmm... That's actually a bit difficult. The best way I can think of doing it without some code in front of me is by grabbing the IDs of all the results from the previous query and passing them through in another `->having()` method call after get query on your second query. This will find all the results matching your second search and then filter out the ones that weren't returned in your previous search.

**Comment by Rezakhaan** [comment]
it's a fantastic idea
could you please give me an example ?
I just try to do this but I face errors.
