### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1463 Non-grouping field 'relevance' is used in HAVING clause

### ISSUE THREAD

**Issue by krisscox** [TomLingham/Laravel-Searchy#56]
This happens in Laravel 5.3, and has happened both for the default search driver and levenshtein.

It would appear to be down to L 5.3 having "strict" mode set to true in the config/database.php file, under the MYSQL connection setting. 

Unsure about a way round this, as my MYSQL isn't amazingly strong, but I've bypassed it for the moment by making that value false.

Hope this can help someone else.

**Comment by iusky** [comment]
Me too。。。。 Help！

**Comment by TomLingham** [comment]
Hi guys. Thanks for letting me know. I don't use php or this package much
anymore so I appreciate you letting me know. I will look at it this weekend
unless you want to submit a PR. But until then, sit tight, I'll have time
to look at it this weekend :)

**Comment by TomLingham** [comment]
Any chance you could please send through some code @krisscox? The Searchy bit should be I all I need to go off 😄

**Comment by TomLingham** [comment]
Closing due to no response. Please open a new issue if you are still having issues :smile:

**Comment by MrSnoozles** [comment]
You can disable strict mode in config/database.php to resolve the error.
