### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by iusky** [TomLingham/Laravel-Searchy#59]
If the input keyword is '
 will be an error
As long as the input keyword to 'or all' will be error.

**Comment by TomLingham** [comment]
Can you please provide a little more information about what the issue is? A repo with reproducing code would be very useful?

**Comment by iusky** [comment]
You can try, 'into the query

**Comment by TomLingham** [comment]
This PR should have fixed your issue :) https://github.com/TomLingham/Laravel-Searchy/pull/63
