### ISSUE TITLE
Joins behave badly

### ISSUE THREAD

**Issue by Gawdl3y** [TomLingham/Laravel-Searchy#6]
Joins used on the search queries don't work very well. Take this for example:
```PHP
$posts = Searchy::posts('name', 'body', 'users.name')->query('Bob')
    ->leftJoin('users', 'user_id', '=', 'users.id')
    ->get(['posts.name', 'body', 'users.id as user_id', 'users.name as user_name']);
```
Rather than receiving an array of objects with the requested columns and their aliases, you get an array of objects with the combined columns of both tables, without their aliases, with the joined table's columns overwriting any with the same name.

**Comment by Spycomb** [comment]
considering @TomLingham  said i don't recomend this , but if you still want to do that you can edit the "BaseSearchDriver.php"

change the line query method

	public function query( $searchString )
	{

		if(\Config::get('searchy::sanitize'))
			$this->searchString = $this->sanitize($searchString);

		$results = \DB::table($this->table)
			->select('*')
			->addSelect($this->buildSelectQuery( $this->searchFields ))
			->orderBy(\Config::get('searchy::fieldName'), 'desc')
			->having(\Config::get('searchy::fieldName'),'>', 0);

		return $results;
	}

to

	public function query( $searchString ,$cols = "*")
	{

		if(\Config::get('searchy::sanitize'))
			$this->searchString = $this->sanitize($searchString);

		$results = \DB::table($this->table)
			->select($cols)
			->addSelect($this->buildSelectQuery( $this->searchFields ))
			->orderBy(\Config::get('searchy::fieldName'), 'desc')
			->having(\Config::get('searchy::fieldName'),'>', 0);

		return $results;
	}

but i haven't tested this, i don't know if this going to have a further errors or something  :cat:

**Comment by TomLingham** [comment]
You can now select specific columns in version 2+

Thanks for your help guys :smile:
