### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by mmjjb** [TomLingham/Laravel-Searchy#60]
**Query:**
Searchy::search('categories')->fields('title')->query($keyword)->getQuery()->limit(3)->get();

**Result**

SQLSTATE[42000]: Syntax error or access violation: 1463 Non-grouping field 'relevance' is used in HAVING clause (SQL: select *, IF(COALESCE(`title`, '') = 'keyword', 100, 0) + IF(COALESCE(`title`, '') LIKE 'keyword%', 50, 0) + IF(COALESCE(`title`, '') LIKE 'K% E% Y% W% O% R% D%', 42, 0) + IF( REPLACE(COALESCE(`title`, ''), '\.', '') LIKE '%k%e%y%w%o%r%d%', ROUND(40 * ( CHAR_LENGTH( 'keyword' ) / CHAR_LENGTH( REPLACE(COALESCE(`title`, ''), ' ', '') ))), 0) + IF(COALESCE(`title`, '') LIKE 'keyword%', 35, 0) + IF( CHAR_LENGTH( TRIM( COALESCE(`title`, '') )) = CHAR_LENGTH( REPLACE( TRIM( COALESCE(`title`, '') ), ' ', '')) AND COALESCE(`title`, '') LIKE BINARY 'K%E%Y%W%O%R%D%', 32, 0) + IF(COALESCE(`title`, '') LIKE '%keyword%', 30, 0) + 8 * ROUND((
CHAR_LENGTH(COALESCE(`title`, '')) - CHAR_LENGTH( REPLACE( LOWER(COALESCE(`title`, '')), lower('keyword'), ''))
) / LENGTH('keyword')) AS relevance from `categories` having `relevance` > 0 order by `relevance` desc limit 3)

**Comment by TomLingham** [comment]
Hi, until I get a chance to look at this a little closer, you can try disabling strict mode in config/database.php to resolve the error. This isn't the best solution but until I have time to fix or someone submits a PR this will get you out of trouble 😄

**Comment by yiluohan1234** [comment]
This is probably a SQL_MODE problem. In your config/database.php, in the connection, change config/database.php 
strict => false

**Comment by jason3w** [comment]
We are having this same issue. Any resolution in the pipeline? 
Thanks

**Comment by TomLingham** [comment]
Hi, did you try disabling strict mode? Did that work for you?

**Comment by jason3w** [comment]
Hey Tom, 
Yep did try that and it works but has many potential downsides. :( 
Otherwise, your script looks amazing. Is it something solvable you think?

**Comment by TomLingham** [comment]
Recommended fix is to run in strict mode due to how the package works. It would have to be rewritten (Probably with a lot more complexity) to get around this.

**Comment by kevosomi** [comment]
Disabling strict mode worked for me. What are the downsides to it though?

**Comment by damms005** [comment]
@kevosomi  check why here: https://stackoverflow.com/questions/39053335/laravel-5-3-syntax-error-or-access-violation-1463-non-grouping-field-distance#comment76376503_39449233
