### ISSUE TITLE
Value of relevance

### ISSUE THREAD

**Issue by Kolesar** [TomLingham/Laravel-Searchy#68]
Hi,

What is the scope of relevance value? I want to make a slider in my search form between 'retrieval' and 'precision', but I do not know scope of the relevance value :/

**Comment by TomLingham** [comment]
Hi Kolesar. The value can be between 0 and any positive number with the default drivers. If you wanted to have a maximum value you would have to determine the highest value for your search results and use that value - which could of course change.
