### ISSUE TITLE
var_dump() or print_r() causes empty page

### ISSUE THREAD

**Issue by ykbks** [TomLingham/Laravel-Searchy#7]
`$members = Searchy::members('name')->query('hussain');`
No problem, page loads.
`var_dump($members);`
page is blank! even the existing markup does not show.

Anything I'm doing wrong?

**Comment by TomLingham** [comment]
Sorry for the late reply. You will need to run:

`Searchy::members('name')->query('hussain')->get();`

I'm not sure why nothing would be rendering after running a var_dump. Most likely cause is that your program is erroring somewhere and that the error are set not to output. Might want to;

- check your server logs
- turn on error reporting in php.ini [http://stackoverflow.com/questions/845021/how-to-get-useful-error-messages-in-php]
