### ISSUE TITLE
Filter table rows before search

### ISSUE THREAD

**Issue by fede91it** [TomLingham/Laravel-Searchy#70]
Hello,

I have a big table containing geocoded items that I filter for a radius of distance from a latitude and longitude coordinates (ex. to match items near 10 km from coordinates). After that I need to order the results by relevance to a given search keyword and is for that I use Searchy with a lot of satisfaction, but I have a limitation that represents for me a big performance weak.

```php
$items = Searchy('items')->fields('name')
                         ->query('foobar')
                         ->getQuery()
                         ->distance($latitude, $longitude, $radius)
                         ->take(10)
                         ->get();
```

`distance` is a local scope of my `Items`-model and is used to call a stored MySQL procedure that calculates the distance between $latitude, $longitude and items' coordinates included in a $radius of distance.

That example works but is very un-performant because the search based on name is performed before the geographic filter so instead of search over 1000 items it searches over 1 million.

I have not found a way to use Searchy AFTER a query filtering, I can not filter the query BEFORE.

Why not extend Eloquent e allow a use of Searchy like this?

```php
$items = Item::distance($latitude, $longitude, $radius)->search('foobar', ['name'])
                                                       ->take(10)
                                                       ->get();
```

It would be a lot more simple and intuitive than now and this use will not force you to do escamotages to work with the native Eloquent system.

What do you think?

**Comment by TomLingham** [comment]
Hi @fede91it thanks for the feedback. Unfortunately Searchy is more of a stop gap and I don't want people to use it where it's so easy to use a more appropriate search and indexing solution. Algolia or Cloudsearch are two great examples.

Ive been meaning to update the readme with my intentions for Searchy moving forward but have been quite time poor.

I do intend to maintain it but don't thing I will be adding new features at this stage.
