### ISSUE TITLE
Class 'Searchy' not found

### ISSUE THREAD

**Issue by leo-coco** [TomLingham/Laravel-Searchy#71]
I followed the instruction to install this package but I can't make it works. I'm using Laravel 5.4

I'd like to use it in my RegisterController.php

```
namespace App\Http\Controllers\Auth;

use Searchy;

class RegisterController extends Controller { 
    public function example () {
        Searchy::search('companies')->fields('name')->query('test')->getQuery()->limit(1)->get();
    }   
}
```

I got the error `Class 'Searchy' not found`

**Comment by kumarrishikesh12** [comment]
use TomLingham\Searchy\SearchBuilder; .. Use this ...

**Comment by leo-coco** [comment]
Here is what I got : Class 'App\Http\Controllers\Auth\Searchy' not found
