### ISSUE TITLE
Searching multiple keywords

### ISSUE THREAD

**Issue by trmccormick** [TomLingham/Laravel-Searchy#74]
Maybe I'm missing something but is it possible to have multiple keyword search using Searchy?

**Comment by TomLingham** [comment]
If you're referring to passing multiple arguments to the `->query()` method, then unfortunately no. If you are using Searchy for something other than user driven search queries then it's probably not going to work quite as you expect. Can you give me more information about how you are using Search? I will try and help out if I can 😄

**Comment by trmccormick** [comment]
We have over a million records in the sample data we were given and need to search across all the fields. So we created a search index field so we can search all the data since passing all the fields were taking several minutes to search. The main issue is If I search for "john doe" I get no results if I search for just "john" then I do get results it seems the search doesn't like multiple keywords.

**Comment by TomLingham** [comment]
It does support searching for multiple words inside a single fields. It also allows for concatenating specific fields in certain scenarios. See https://github.com/TomLingham/Laravel-Searchy#searching-joinedconcatenated-columns

If that still doesn't answer your question, some code would be helpful for troubleshooting.

**Comment by trmccormick** [comment]
I was able to solve this another way thanks.
