### ISSUE TITLE
Docs hydrate

### ISSUE THREAD

**Issue by covert8** [TomLingham/Laravel-Searchy#77]
Hi there,

First and foremost thanks for all the good word, simply splendid stuff.

I was looking at the documentation and saw that the recommendation for the use of hydrate. however I got strange errors because of the way searchy returns the data. What I believe is that you return a kind of object instead of regular json, thus requirering a toArray() afther the get().

Is this indeed true and if so would you kindly update to docs ?

example:
 \App\Product::hydrate(Searchy::products('naam')	->query($searchvalue)->getQuery()->where('bakkerij_id','=',$bakkerij->id)->having('relevance','>',20)->get()->toArray());

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
