### ISSUE TITLE
Error when use using quotes

### ISSUE THREAD

**Issue by roxik** [TomLingham/Laravel-Searchy#82]
Error when use using quotes.

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '% R% E% D%', 42, 0)  ... `

```
$query = "dishon'red";

dd(Searchy::products('name')->query($query)->get());
```

check ConsecutiveCharactersUnicodeMatcher plz

**Comment by TomLingham** [comment]
As mentioned in the README
```
PLEASE NOTE: There is no sanitization of strings passed through to the FuzzySearchUnicodeDriver prior to inserting into raw MySQL statements. You will have to sanitize the string yourself first or risk opening up your application to SQL injection attacks. You have been warned.
```
