### ISSUE TITLE
Proposal: option to remove the relevance fieldName

### ISSUE THREAD

**Issue by mazyvan** [TomLingham/Laravel-Searchy#85]
I know it is posible to rename the field, but i would like to have an option on the configuration to remove it after the query, because I'm querying the database with different texts and I realize I can not use 
`->query($text1)->query($text2)`
because is like querying the query and what I want is a join.
So I'm trying to use `array_unique(array_merge($workers, $moreWorkers), SORT_REGULAR);`

**Comment by TomLingham** [comment]
Can you filter it out after making the query? Will that solve your problem?
