### ISSUE TITLE
Search with translations in another table

### ISSUE THREAD

**Issue by johnef** [TomLingham/Laravel-Searchy#86]
Hi I am using this package [Laravel Translation](https://github.com/dimsav/laravel-translatable ) How to get it working with this package this Laravel Translation package has function called `whereTranslation` but here how to use it with something like 
`$products = Searchy::search('products')->fields('name', 'tags')->query($search)->get();` which name and tags is another table.

Thanks

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
