### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1463 Non-grouping field 'relevance' is 

### ISSUE THREAD

**Issue by ankit20893** [TomLingham/Laravel-Searchy#89]
SQLSTATE[42000]: Syntax error or access violation: 1463 Non-grouping field 'relevance' is

**Comment by IslamEso** [comment]
As a temporary solution:


Check in the config/database.php file in the mysql conection that the strict is false:

`'strict' => false,`

If is true, put in false.

-----
Copied from : https://stackoverflow.com/a/39449233

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
