### ISSUE TITLE
Searchy returns Illuminate/Collection, not array?

### ISSUE THREAD

**Issue by david-knigge** [TomLingham/Laravel-Searchy#91]
`var_dump(Searchy::users('name', 'email')->query(...)->get());`

Returns the following

`object(Illuminate\Support\Collection)#250 (1) {
  ["items":protected]=>
  array(3) {
...
`

Of course it's easily fixed by:

`Searchy::users('name', 'email')->query(...)->get()->toArray()`

But this seems unintended behaviour given the documentation.

Laravel 5.6, Searchy 2.0

**Comment by TomLingham** [comment]
Ah, yes. You are correct, however the documentation is incorrect. It is returning an Illuminate collection. I'll update. Thank you.

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
