### ISSUE TITLE
Handling special Characters

### ISSUE THREAD

**Issue by mugwag** [TomLingham/Laravel-Searchy#93]
Searchy is working great, but spaces and hypens seem to confuse it. As with Google, these can often be ignored. But with Searchy, lets say I search for my name "mugwag" will come up first in a list, but " mugwag" (note the space) will yield 0 results. Same for hypens - "rx500" will find a record called rx-500, but "rx 500" won't. 
Is there an option to ignore special characters?

**Comment by TomLingham** [comment]
Unfortunately this isn't trivial but a matcher class could be created. I would accept a PR for the appropriate matcher.

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
