### ISSUE TITLE
levenshtein drive keeps processing and does not bring result

### ISSUE THREAD

**Issue by ShayanSolution** [TomLingham/Laravel-Searchy#95]
Hi

I have used levenshtein driver. As soon as i use it my CPU consumption goes to 100% and it keeps processing and not bring back any result. I have already created levenshtein function from res folder. 

Platform: Windows 10
Tool: WAMP
MySQL: 5.7.19
PHP: 5.6
Laravel: 5.1

**Comment by TomLingham** [comment]
It's only experimental and unfortunately is extremely taxing on resources and not able to be optimised within the scope of this project. I'd recommend using a service such as Algolio.
