### ISSUE TITLE
Can't return multiple specific columns

### ISSUE THREAD

**Issue by austinwitherspoon** [TomLingham/Laravel-Searchy#96]
If I use a string in a query like 
`$users = Searchy::users('first_name::last_name')->select('first_name')->query('John Smith')->get();` 

it works fine, but if I change that to an array like 
`$users = Searchy::users('first_name::last_name')->select(['first_name', 'last_name'])->query('John Smith')->get();`

it fails, telling me the function expected a string, not an array.

**Comment by pendledt** [comment]
I think it requires comma separated values e.g.

`$users = Searchy::users('first_name::last_name')->select('first_name', 'last_name')->query('John Smith')->get();`

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
