### ISSUE TITLE
Very slow query causing 400% slow down of results

### ISSUE THREAD

**Issue by jonathan-bird** [TomLingham/Laravel-Searchy#97]
There is a bit of code here that's very slow due to the fact you're calling get column listing which takes approx 300ms just to get that result: https://github.com/TomLingham/Laravel-Searchy/blob/master/src/SearchDrivers/BaseSearchDriver.php#L123

The query without this I can get down to <50ms but with this, you're slowing it down to almost 400ms on average, which on a big loop, is very expensive in terms of speed.

I'd personally suggest just removing this or having an option to not run the query. In my branch I've just removed it as I don't need it.

**Comment by TomLingham** [comment]
Please see https://github.com/TomLingham/Laravel-Searchy/issues/117
